# Sample .travis.yml for R projects
language: r
cache: packages
matrix:
 include:
   - os: osx
     r: release
     sudo: required
   - os: osx
     r: devel
     sudo: required
     r_packages:
      - plyr
      - stringr
      - tidyr
      - lubridate
      - dplyr
      - units
   - os: linux
     r: release
     sudo: required
   - os: linux
     r: devel
     sudo: required
 allow_failures:
   - os: osx
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y libudunits2-dev; fi
warnings_are_errors: true


