# Sample .travis.yml for R projects
language: r
cache: packages
matrix:
 include:
   - os: osx
     r: release
     sudo: required
   - os: osx
     r: devel
     sudo: required
     r_packages:
      - plyr
      - stringr
      - tidyr
      - lubridate
   - os: linux
     r: release
     sudo: required
   - os: linux
     r: devel
     sudo: required
 allow_failures:
   - r: devel
warnings_are_errors: true


